#!/bin/bash
#
# File containing the following:
#
# ANYKERNEL=/path/to/anykernel
# OUTPUT=/path/to/output
#
SETTINGS=~/bin/paths-kernel.sh

# zImage location within kernel tree
ZIMAGE=arch/arm/boot/zImage

if [ -f ~/bin/paths-kernel.sh ]; then
    source ~/bin/paths-kernel.sh
else
    echo "Settings file ('$SETTINGS') doesn't exist. Aborting."
    exit 1
fi

if [ -z ${ANYKERNEL+x} ]; then
    echo "ANYKERNEL is unset. Aborting."
    exit 1
fi

if [ -z ${OUTPUT+x} ]; then
    echo "OUTPUT is unset. Aborting."
    exit 1
fi

DATE=$(date +%Y%m%d-%H%M)
PWD=$(pwd)

# copy files
if [ -f $PWD/$ZIMAGE ]; then
    cp -v $PWD/$ZIMAGE $ANYKERNEL/kernel/zImage
else
    echo "zImage doesn't exist. Aborting."
    exit 1
fi

# zip it
command -v zip >/dev/null 2>&1 || { echo >&2 "I require zip but it's not installed. Aborting."; exit 1; }
if [ -d $ANYKERNEL ]; then
    cd $ANYKERNEL
    zip -r9 $OUTPUT/kernel-$DATE.zip *
else
    echo "AnyKernel path ('$ANYKERNEL') doesn't exists. Aborting."
    exit 1
fi

# return
cd $PWD
